# Generated by Django 6.1 on 2026-08-31 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_name', models.CharField(default='Semester Installment', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI / QR Code'), ('NETBANKING', 'Net Banking / NEFT / RTGS'), ('CARD', 'Debit / Credit Card'), ('CASH', 'Cash Counter'), ('CHEQUE', 'Cheque / DD')], default='UPI', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, help_text='UTR / UPI Ref / Cheque No.', max_length=100, null=True)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='fee_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved / Credited'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facultyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='core.studentprofile')),
            ],
        ),
    ]
